const phData = {

  /* ============================
     ABRA
  ============================ */
  "Abra": [
    { city: "Bangued", zip: "2800" },
    { city: "Boliney", zip: "2815" },
    { city: "Bucay", zip: "2805" },
    { city: "Bucloc", zip: "2817" },
    { city: "Daguioman", zip: "2816" },
    { city: "Danglas", zip: "2824" },
    { city: "Dolores", zip: "2801" },
    { city: "La Paz", zip: "2826" },
    { city: "Lacub", zip: "2821" },
    { city: "Lagangilang", zip: "2802" },
    { city: "Langiden", zip: "2803" },
    { city: "Licuan-Baay", zip: "2819" },
    { city: "Luba", zip: "2813" },
    { city: "Malibcong", zip: "2820" },
    { city: "Manabo", zip: "2810" },
    { city: "Peñarrubia", zip: "2804" },
    { city: "Pidigan", zip: "2806" },
    { city: "Pilar", zip: "2812" },
    { city: "Sallapadan", zip: "2818" },
    { city: "San Isidro", zip: "2809" },
    { city: "San Juan", zip: "2823" },
    { city: "San Quintin", zip: "2808" },
    { city: "Tayum", zip: "2807" },
    { city: "Tineg", zip: "2822" },
    { city: "Tubo", zip: "2814" },
    { city: "Villaviciosa", zip: "2811" }
  ],

  /* ============================
     AGUSAN DEL NORTE
  ============================ */
  "Agusan del Norte": [
    { city: "Buenavista", zip: "8601" },
    { city: "Butuan City", zip: "8600" },
    { city: "Cabadbaran City", zip: "8605" },
    { city: "Carmen", zip: "8603" },
    { city: "Jabonga", zip: "8607" },
    { city: "Kitcharao", zip: "8609" },
    { city: "Las Nieves", zip: "8610" },
    { city: "Magallanes", zip: "8604" },
    { city: "Nasipit", zip: "8602" },
    { city: "Remedios T. Romualdez", zip: "8611" },
    { city: "Santiago", zip: "8608" },
    { city: "Tubay", zip: "8606" }
  ],

  /* ============================
     AGUSAN DEL SUR
  ============================ */
  "Agusan del Sur": [
    { city: "Bayugan City", zip: "8502" },
    { city: "Bunawan", zip: "8506" },
    { city: "La Paz", zip: "8508" },
    { city: "Loreto", zip: "8507" },
    { city: "Prosperidad", zip: "8500" },
    { city: "Rosario", zip: "8504" },
    { city: "San Francisco", zip: "8501" },
    { city: "San Luis", zip: "8511" },
    { city: "Santa Josefa", zip: "8512" },
    { city: "Sibagat", zip: "8503" },
    { city: "Talacogon", zip: "8510" },
    { city: "Trento", zip: "8505" },
    { city: "Veruela", zip: "8509" }
  ],

  /* ============================
     AKLAN
  ============================ */
  "Aklan": [
    { city: "Altavas", zip: "5616" },
    { city: "Balete", zip: "5614" },
    { city: "Banga", zip: "5601" },
    { city: "Batan", zip: "5615" },
    { city: "Buruanga", zip: "5609" },
    { city: "Ibajay", zip: "5613" },
    { city: "Kalibo", zip: "5600" },
    { city: "Lezo", zip: "5605" },
    { city: "Libacao", zip: "5602" },
    { city: "Madalag", zip: "5603" },
    { city: "Makato", zip: "5611" },
    { city: "Malay (incl. Boracay)", zip: "5608" },
    { city: "Malinao", zip: "5606" },
    { city: "Nabas", zip: "5607" },
    { city: "New Washington", zip: "5610" },
    { city: "Numancia", zip: "5604" },
    { city: "Tangalan", zip: "5612" }
  ],

  /* ============================
     ALBAY
  ============================ */
  "Albay": [
    { city: "Bacacay", zip: "4509" },
    { city: "Camalig", zip: "4502" },
    { city: "Daraga", zip: "4501" },
    { city: "Guinobatan", zip: "4503" },
    { city: "Jovellar", zip: "4515" },
    { city: "Legazpi City", zip: "4500" },
    { city: "Libon", zip: "4507" },
    { city: "Ligao City", zip: "4504" },
    { city: "Malilipot", zip: "4510" },
    { city: "Malinao", zip: "4512" },
    { city: "Manito", zip: "4514" },
    { city: "Oas", zip: "4505" },
    { city: "Pio Duran", zip: "4516" },
    { city: "Polangui", zip: "4506" },
    { city: "Rapu-Rapu", zip: "4517" },
    { city: "Santo Domingo", zip: "4511" },
    { city: "Tabaco City", zip: "4513" },
    { city: "Tiwi", zip: "4513" }
  ],

  /* ============================
     ANTIQUE
  ============================ */
  "Antique": [
    { city: "Anini-y", zip: "5717" },
    { city: "Barbaza", zip: "5706" },
    { city: "Belison", zip: "5701" },
    { city: "Bugasong", zip: "5704" },
    { city: "Caluya", zip: "5711" },
    { city: "Culasi", zip: "5708" },
    { city: "Hamtic", zip: "5715" },
    { city: "Laua-an", zip: "5705" },
    { city: "Libertad", zip: "5710" },
    { city: "Pandan", zip: "5712" },
    { city: "Patnongon", zip: "5702" },
    { city: "San Jose", zip: "5700" },
    { city: "San Remigio", zip: "5714" },
    { city: "Sebaste", zip: "5709" },
    { city: "Sibalom", zip: "5713" },
    { city: "Tibiao", zip: "5707" },
    { city: "Valderrama", zip: "5716" }
  ],

  /* ============================
     APAYAO
  ============================ */
  "Apayao": [
    { city: "Calanasan", zip: "3812" },
    { city: "Conner", zip: "3807" },
    { city: "Flora", zip: "3810" },
    { city: "Kabugao", zip: "3809" },
    { city: "Luna", zip: "3813" },
    { city: "Pudtol", zip: "3811" },
    { city: "Santa Marcela", zip: "3808" }
  ],

  /* ============================
     AURORA
  ============================ */
  "Aurora": [
    { city: "Baler", zip: "3200" },
    { city: "Casiguran", zip: "3204" },
    { city: "Dilasag", zip: "3205" },
    { city: "Dinalungan", zip: "3206" },
    { city: "Dingalan", zip: "3207" },
    { city: "Dipaculao", zip: "3203" },
    { city: "Maria Aurora", zip: "3202" },
    { city: "San Luis", zip: "3201" }
  ],

  /* ============================
     BASILAN
  ============================ */
  "Basilan": [
    { city: "Akbar", zip: "7309" },
    { city: "Al-Barka", zip: "7308" },
    { city: "Hadji Mohammad Ajul", zip: "7310" },
    { city: "Hadji Muhtamad", zip: "7311" },
    { city: "Isabela City", zip: "7300" },
    { city: "Lamitan City", zip: "7302" },
    { city: "Lantawan", zip: "7301" },
    { city: "Maluso", zip: "7303" },
    { city: "Sumisip", zip: "7305" },
    { city: "Tabuan-Lasa", zip: "7307" },
    { city: "Tipo-Tipo", zip: "7304" },
    { city: "Ungkaya Pukan", zip: "7306" }
  ],

  /* ============================
     BATAAN
  ============================ */
  "Bataan": [
    { city: "Abucay", zip: "2102" },
    { city: "Bagac", zip: "2107" },
    { city: "Balanga City", zip: "2100" },
    { city: "Dinalupihan", zip: "2110" },
    { city: "Hermosa", zip: "2111" },
    { city: "Limay", zip: "2103" },
    { city: "Mariveles", zip: "2105" },
    { city: "Morong", zip: "2108" },
    { city: "Orani", zip: "2112" },
    { city: "Orion", zip: "2104" },
    { city: "Pilar", zip: "2101" },
    { city: "Samal", zip: "2113" }
  ],

  /* ============================
     BATANES
  ============================ */
  "Batanes": [
    { city: "Basco", zip: "3900" },
    { city: "Itbayat", zip: "3905" },
    { city: "Ivana", zip: "3902" },
    { city: "Mahatao", zip: "3901" },
    { city: "Sabtang", zip: "3904" },
    { city: "Uyugan", zip: "3903" }
  ],

  /* ============================
     BATANGAS
  ============================ */
  "Batangas": [
    { city: "Agoncillo", zip: "4211" },
    { city: "Alitagtag", zip: "4205" },
    { city: "Balayan", zip: "4213" },
    { city: "Balete", zip: "4219" },
    { city: "Batangas City", zip: "4200" },
    { city: "Bauan", zip: "4201" },
    { city: "Calaca", zip: "4212" },
    { city: "Calatagan", zip: "4215" },
    { city: "Cuenca", zip: "4222" },
    { city: "Ibaan", zip: "4230" },
    { city: "Laurel", zip: "4221" },
    { city: "Lemery", zip: "4209" },
    { city: "Lian", zip: "4216" },
    { city: "Lipa City", zip: "4217" },
    { city: "Lobo", zip: "4229" },
    { city: "Mabini", zip: "4202" },
    { city: "Malvar", zip: "4233" },
    { city: "Mataas na Kahoy", zip: "4223" },
    { city: "Nasugbu", zip: "4231" },
    { city: "Padre Garcia", zip: "4224" },
    { city: "Rosario", zip: "4225" },
    { city: "San Jose", zip: "4227" },
    { city: "San Juan", zip: "4226" },
    { city: "San Luis", zip: "4210" },
    { city: "San Nicolas", zip: "4207" },
    { city: "San Pascual", zip: "4204" },
    { city: "Santa Teresita", zip: "4206" },
    { city: "Santo Tomas", zip: "4234" },
    { city: "Taal", zip: "4208" },
    { city: "Talisay", zip: "4220" },
    { city: "Tanauan City", zip: "4232" },
    { city: "Taysan", zip: "4235" },
    { city: "Tingloy", zip: "4203" },
    { city: "Tuy", zip: "4214" }
  ],

  /* ============================
     BENGUET
  ============================ */
  "Benguet": [
    { city: "Atok", zip: "2612" },
    { city: "Baguio City", zip: "2600" },
    { city: "Bakun", zip: "2610" },
    { city: "Bokod", zip: "2605" },
    { city: "Buguias", zip: "2607" },
    { city: "Itogon", zip: "2604" },
    { city: "Kabayan", zip: "2606" },
    { city: "Kapangan", zip: "2613" },
    { city: "Kibungan", zip: "2611" },
    { city: "La Trinidad", zip: "2601" },
    { city: "Mankayan", zip: "2608" },
    { city: "Sablan", zip: "2614" },
    { city: "Tuba", zip: "2603" },
    { city: "Tublay", zip: "2602" }
  ],

  /* ============================
     BILIRAN
  ============================ */
  "Biliran": [
    { city: "Almeria", zip: "6544" },
    { city: "Biliran", gzip: "6549" },
    { city: "Cabucgayan", zip: "6550" },
    { city: "Caibiran", zip: "6548" },
    { city: "Culaba", zip: "6547" },
    { city: "Kawayan", zip: "6545" },
    { city: "Maripipi", zip: "6546" },
    { city: "Naval", zip: "6543" }
  ],

  /* ============================
     BOHOL
  ============================ */
  "Bohol": [
    { city: "Alburquerque", zip: "6302" },
    { city: "Alicia", zip: "6314" },
    { city: "Anda", zip: "6311" },
    { city: "Antequera", zip: "6335" },
    { city: "Baclayon", zip: "6301" },
    { city: "Balilihan", zip: "6342" },
    { city: "Batuan", zip: "6318" },
    { city: "Bien Unido", zip: "6320" },
    { city: "Bilar", zip: "6317" },
    { city: "Buenavista", zip: "6333" },
    { city: "Calape", zip: "6328" },
    { city: "Candijay", zip: "6312" },
    { city: "Carmen", zip: "6319" },
    { city: "Catigbian", zip: "6343" },
    { city: "Clarin", zip: "6334" },
    { city: "Corella", zip: "6337" },
    { city: "Cortes", zip: "6341" },
    { city: "Dagohoy", zip: "6322" },
    { city: "Danao", zip: "6344" },
    { city: "Dauis", zip: "6330" },
    { city: "Dimiao", zip: "6305" },
    { city: "Duero", zip: "6309" },
    { city: "Garcia Hernandez", zip: "6307" },
    { city: "Getafe", zip: "6331" },
    { city: "Guindulman", zip: "6310" },
    { city: "Inabanga", zip: "6332" },
    { city: "Jagna", zip: "6308" },
    { city: "Lila", zip: "6304" },
    { city: "Loay", zip: "6303" },
    { city: "Loboc", zip: "6316" },
    { city: "Loon", zip: "6327" },
    { city: "Mabini", zip: "6315" },
    { city: "Maribojoc", zip: "6336" },
    { city: "Panglao", zip: "6340" },
    { city: "Pilar", zip: "6321" },
    { city: "President Carlos P. Garcia", zip: "6326" },
    { city: "Sagbayan", zip: "6338" },
    { city: "San Isidro", zip: "6345" },
    { city: "San Miguel", zip: "6323" },
    { city: "Sevilla", zip: "6346" },
    { city: "Sikatuna", zip: "6339" },
    { city: "Tagbilaran City", zip: "6300" },
    { city: "Talibon", zip: "6325" },
    { city: "Trinidad", zip: "6324" },
    { city: "Tubigon", zip: "6329" },
    { city: "Ubay", zip: "6315" }
  ],

  /* ============================
     BUKIDNON
  ============================ */
  "Bukidnon": [
    { city: "Baungon", zip: "8707" },
    { city: "Cabanglasan", zip: "8723" },
    { city: "Damulog", zip: "8714" },
    { city: "Dangcagan", zip: "8710" },
    { city: "Don Carlos", zip: "8712" },
    { city: "Impasugong", zip: "8702" },
    { city: "Kadingilan", zip: "8713" },
    { city: "Kalilangan", zip: "8718" },
    { city: "Kibawe", zip: "8720" },
    { city: "Kitaotao", zip: "8719" },
    { city: "Lantapan", zip: "8722" },
    { city: "Libona", zip: "8708" },
    { city: "Malaybalay City", zip: "8700" },
    { city: "Malitbog", zip: "8704" },
    { city: "Manolo Fortich", zip: "8703" },
    { city: "Maramag", zip: "8714" },
    { city: "Pangantucan", zip: "8721" },
    { city: "Quezon", zip: "8715" },
    { city: "San Fernando", zip: "8711" },
    { city: "Sumilao", zip: "8701" },
    { city: "Talakag", zip: "8705" },
    { city: "Valencia City", zip: "8709" }
  ],

  /* ============================
     BULACAN
  ============================ */
  "Bulacan": [
    { city: "Angat", zip: "3012" },
    { city: "Balagtas", zip: "3016" },
    { city: "Baliuag", zip: "3006" },
    { city: "Bocaue", zip: "3018" },
    { city: "Bulakan", zip: "3017" },
    { city: "Bustos", zip: "3007" },
    { city: "Calumpit", zip: "3003" },
    { city: "Doña Remedios Trinidad", zip: "3009" },
    { city: "Guiguinto", zip: "3015" },
    { city: "Hagonoy", zip: "3002" },
    { city: "Malolos City", zip: "3000" },
    { city: "Marilao", zip: "3019" },
    { city: "Meycauayan City", zip: "3020" },
    { city: "Norzagaray", zip: "3013" },
    { city: "Obando", zip: "3021" },
    { city: "Pandi", zip: "3014" },
    { city: "Paombong", zip: "3001" },
    { city: "Plaridel", zip: "3004" },
    { city: "Pulilan", zip: "3005" },
    { city: "San Ildefonso", zip: "3010" },
    { city: "San Jose del Monte City", zip: "3023" },
    { city: "San Miguel", zip: "3011" },
    { city: "San Rafael", zip: "3008" },
    { city: "Santa Maria", zip: "3022" }
  ],

  /* ============================
     CAGAYAN
  ============================ */
  "Cagayan": [
    { city: "Abulug", zip: "3517" },
    { city: "Alcala", zip: "3505" },
    { city: "Allacapan", zip: "3516" },
    { city: "Amulung", zip: "3506" },
    { city: "Aparri", zip: "3515" },
    { city: "Baggao", zip: "3507" },
    { city: "Ballesteros", zip: "3516" },
    { city: "Buguey", zip: "3511" },
    { city: "Calayan", zip: "3520" },
    { city: "Camalaniugan", zip: "3510" },
    { city: "Claveria", zip: "3519" },
    { city: "Enrile", zip: "3501" },
    { city: "Gattaran", zip: "3508" },
    { city: "Gonzaga", zip: "3513" },
    { city: "Iguig", zip: "3502" },
    { city: "Lal-lo", zip: "3509" },
    { city: "Pamplona", zip: "3512" },
    { city: "Peñablanca", zip: "3500" },
    { city: "Piat", zip: "3527" },
    { city: "Rizal", zip: "3521" },
    { city: "Sanchez-Mira", zip: "3518" },
    { city: "Santa Ana", zip: "3514" },
    { city: "Santa Praxedes", zip: "3520" },
    { city: "Santa Teresita", zip: "3512" },
    { city: "Santo Niño", zip: "3525" },
    { city: "Solana", zip: "3503" },
    { city: "Tuao", zip: "3524" }
  ],

  /* ============================
     CAMARINES NORTE
  ============================ */
  "Camarines Norte": [
    { city: "Basud", zip: "4608" },
    { city: "Capalonga", zip: "4607" },
    { city: "Daet", zip: "4600" },
    { city: "Jose Panganiban", zip: "4606" },
    { city: "Labo", zip: "4604" },
    { city: "Mercedes", zip: "4601" },
    { city: "Paracale", zip: "4605" },
    { city: "San Lorenzo Ruiz", zip: "4612" },
    { city: "San Vicente", zip: "4609" },
    { city: "Santa Elena", zip: "4611" },
    { city: "Talisay", zip: "4602" },
    { city: "Vinzons", zip: "4603" }
  ],

  /* ============================
     CAMARINES SUR
  ============================ */
  "Camarines Sur": [
    { city: "Baao", zip: "4432" },
    { city: "Balatan", zip: "4436" },
    { city: "Bato", zip: "4435" },
    { city: "Bombon", zip: "4404" },
    { city: "Buhi", zip: "4433" },
    { city: "Bula", zip: "4430" },
    { city: "Cabusao", zip: "4406" },
    { city: "Calabanga", zip: "4405" },
    { city: "Camaligan", zip: "4401" },
    { city: "Canaman", zip: "4402" },
    { city: "Caramoan", zip: "4429" },
    { city: "Del Gallego", zip: "4411" },
    { city: "Gainza", zip: "4412" },
    { city: "Garchitorena", zip: "4428" },
    { city: "Goa", zip: "4422" },
    { city: "Iriga City", zip: "4431" },
    { city: "Lagonoy", zip: "4425" },
    { city: "Libmanan", zip: "4407" },
    { city: "Lupi", zip: "4409" },
    { city: "Magarao", zip: "4403" },
    { city: "Milaor", zip: "4413" },
    { city: "Minalabac", zip: "4414" },
    { city: "Nabua", zip: "4434" },
    { city: "Naga City", zip: "4400" },
    { city: "Ocampo", zip: "4419" },
    { city: "Pamplona", zip: "4408" },
    { city: "Pasacao", zip: "4417" },
    { city: "Pili", zip: "4418" },
    { city: "Presentacion", zip: "4427" },
    { city: "Ragay", zip: "4410" },
    { city: "Sagñay", zip: "4420" },
    { city: "San Fernando", zip: "4415" },
    { city: "San Jose", zip: "4423" },
    { city: "Sipocot", zip: "4408" },
    { city: "Siruma", zip: "4426" },
    { city: "Tigaon", zip: "4421" },
    { city: "Tinambac", zip: "4422" }
  ],

  /* ============================
     CAMIGUIN
  ============================ */
  "Camiguin": [
    { city: "Catarman", zip: "9104" },
    { city: "Guinsiliban", zip: "9102" },
    { city: "Mahinog", zip: "9101" },
    { city: "Mambajao", zip: "9100" },
    { city: "Sagay", zip: "9103" }
  ],

  /* ============================
     CAPIZ
  ============================ */
  "Capiz": [
    { city: "Cuartero", zip: "5808" },
    { city: "Dao", zip: "5800" },
    { city: "Dumalag", zip: "5813" },
    { city: "Dumarao", zip: "5812" },
    { city: "Ivisan", zip: "5805" },
    { city: "Jamindan", zip: "5806" },
    { city: "Maayon", zip: "5809" },
    { city: "Mambusao", zip: "5810" },
    { city: "Panay", zip: "5801" },
    { city: "Panitan", zip: "5815" },
    { city: "Pilar", zip: "5804" },
    { city: "Pontevedra", zip: "5802" },
    { city: "President Roxas", zip: "5803" },
    { city: "Roxas City", zip: "5800" },
    { city: "Sapi-an", zip: "5816" },
    { city: "Sigma", zip: "5807" },
    { city: "Tapaz", zip: "5814" }
  ],

  /* ============================
     CATANDUANES
  ============================ */
  "Catanduanes": [
    { city: "Bagamanoc", zip: "4807" },
    { city: "Baras", zip: "4803" },
    { city: "Bato", zip: "4801" },
    { city: "Caramoran", zip: "4808" },
    { city: "Gigmoto", zip: "4804" },
    { city: "Pandan", zip: "4817" },
    { city: "Panganiban", zip: "4813" },
    { city: "San Andres", zip: "4805" },
    { city: "San Miguel", zip: "4801" },
    { city: "Viga", zip: "4802" },
    { city: "Virac", zip: "4800" }
  ],

  /* ============================
     CAVITE
  ============================ */
  "Cavite": [
    { city: "Alfonso", zip: "4123" },
    { city: "Amadeo", zip: "4119" },
    { city: "Bacoor City", zip: "4102" },
    { city: "Carmona", zip: "4116" },
    { city: "Cavite City", zip: "4100" },
    { city: "Dasmariñas City", zip: "4114" },
    { city: "General Emilio Aguinaldo", zip: "4124" },
    { city: "General Mariano Alvarez", zip: "4117" },
    { city: "General Trias", zip: "4107" },
    { city: "Imus City", zip: "4103" },
    { city: "Indang", zip: "4122" },
    { city: "Kawit", zip: "4104" },
    { city: "Magallanes", zip: "4113" },
    { city: "Maragondon", zip: "4112" },
    { city: "Mendez", zip: "4121" },
    { city: "Naic", zip: "4110" },
    { city: "Noveleta", zip: "4105" },
    { city: "Rosario", zip: "4106" },
    { city: "Silang", zip: "4118" },
    { city: "Tagaytay City", zip: "4120" },
    { city: "Tanza", zip: "4108" },
    { city: "Ternate", zip: "4111" },
    { city: "Trece Martires City", zip: "4109" }
  ],
  /* ============================
     CEBU
  ============================ */
  "Cebu": [
    { city: "Alcantara", zip: "6033" },
    { city: "Alcoy", zip: "6025" },
    { city: "Alegria", zip: "6030" },
    { city: "Aloguinsan", zip: "6040" },
    { city: "Argao", zip: "6021" },
    { city: "Asturias", zip: "6042" },
    { city: "Badian", zip: "6031" },
    { city: "Balamban", zip: "6041" },
    { city: "Bantayan", zip: "6052" },
    { city: "Barili", zip: "6036" },
    { city: "Bogo City", zip: "6010" },
    { city: "Boljoon", zip: "6024" },
    { city: "Borbon", zip: "6008" },
    { city: "Carcar City", zip: "6019" },
    { city: "Carmen", zip: "6005" },
    { city: "Catmon", zip: "6006" },
    { city: "Cebu City", zip: "6000" },
    { city: "Compostela", zip: "6003" },
    { city: "Consolacion", zip: "6001" },
    { city: "Cordova", zip: "6017" },
    { city: "Daanbantayan", zip: "6013" },
    { city: "Dalaguete", zip: "6022" },
    { city: "Danao City", zip: "6004" },
    { city: "Dumanjug", zip: "6035" },
    { city: "Ginatilan", zip: "6028" },
    { city: "Lapu-Lapu City", zip: "6015" },
    { city: "Liloan", zip: "6002" },
    { city: "Madridejos", zip: "6053" },
    { city: "Malabuyoc", zip: "6029" },
    { city: "Mandaue City", zip: "6014" },
    { city: "Medellin", zip: "6012" },
    { city: "Minglanilla", zip: "6046" },
    { city: "Moalboal", zip: "6032" },
    { city: "Naga City", zip: "6037" },
    { city: "Oslob", zip: "6025" },
    { city: "Pilar", zip: "6048" },
    { city: "Pinamungajan", zip: "6039" },
    { city: "Poro", zip: "6049" },
    { city: "Ronda", zip: "6034" },
    { city: "Samboan", zip: "6027" },
    { city: "San Fernando", zip: "6018" },
    { city: "San Francisco", zip: "6050" },
    { city: "San Remigio", zip: "6011" },
    { city: "Santa Fe", zip: "6047" },
    { city: "Sibonga", zip: "6020" },
    { city: "Sogod", zip: "6007" },
    { city: "Tabogon", zip: "6009" },
    { city: "Tabuelan", zip: "6044" },
    { city: "Talisay City", zip: "6045" },
    { city: "Toledo City", zip: "6038" },
    { city: "Tuburan", zip: "6043" },
    { city: "Tudela", zip: "6051" }
  ],

  /* ============================
     COTABATO (NORTH COTABATO)
  ============================ */
  "Cotabato": [
    { city: "Alamada", zip: "9413" },
    { city: "Aleosan", zip: "9415" },
    { city: "Antipas", zip: "9414" },
    { city: "Arakan", zip: "9417" },
    { city: "Banisilan", zip: "9411" },
    { city: "Carmen", zip: "9408" },
    { city: "Kabacan", zip: "9407" },
    { city: "Kidapawan City", zip: "9400" },
    { city: "Libungan", zip: "9412" },
    { city: "M'lang", zip: "9402" },
    { city: "Magpet", zip: "9404" },
    { city: "Makilala", zip: "9401" },
    { city: "Matalam", zip: "9406" },
    { city: "Midsayap", zip: "9410" },
    { city: "Pigcawayan", zip: "9409" },
    { city: "Pikit", zip: "9403" },
    { city: "President Roxas", zip: "9405" },
    { city: "Tulunan", zip: "9403" }
  ],

  /* ============================
     DAVAO DEL NORTE
  ============================ */
  "Davao del Norte": [
    { city: "Asuncion", zip: "8102" },
    { city: "Braulio Dujali", zip: "8105" },
    { city: "Carmen", zip: "8101" },
    { city: "Island Garden City of Samal", zip: "8119" },
    { city: "Kapalong", zip: "8113" },
    { city: "New Corella", zip: "8104" },
    { city: "Panabo City", zip: "8105" },
    { city: "Samal City", zip: "8120" },
    { city: "Sto. Tomas", zip: "8112" },
    { city: "Tagum City", zip: "8100" },
    { city: "Talaingod", zip: "8115" }
  ],

  /* ============================
     DAVAO DEL SUR
  ============================ */
  "Davao del Sur": [
    { city: "Bansalan", zip: "8005" },
    { city: "Davao City", zip: "8000" },
    { city: "Digos City", zip: "8002" },
    { city: "Hagonoy", zip: "8006" },
    { city: "Kiblawan", zip: "8008" },
    { city: "Magsaysay", zip: "8004" },
    { city: "Malalag", zip: "8010" },
    { city: "Matanao", zip: "8011" },
    { city: "Padada", zip: "8007" },
    { city: "Santa Cruz", zip: "8001" },
    { city: "Sulop", zip: "8009" }
  ],

  /* ============================
     DAVAO ORIENTAL
  ============================ */
  "Davao Oriental": [
    { city: "Baganga", zip: "8204" },
    { city: "Banaybanay", zip: "8208" },
    { city: "Boston", zip: "8206" },
    { city: "Caraga", zip: "8203" },
    { city: "Cateel", zip: "8205" },
    { city: "Governor Generoso", zip: "8210" },
    { city: "Lupon", zip: "8207" },
    { city: "Manay", zip: "8202" },
    { city: "Mati City", zip: "8200" },
    { city: "San Isidro", zip: "8209" },
    { city: "Tarragona", zip: "8201" }
  ],

  /* ============================
     EASTERN SAMAR
  ============================ */
  "Eastern Samar": [
    { city: "Arteche", zip: "6822" },
    { city: "Balangkayan", zip: "6801" },
    { city: "Borongan City", zip: "6800" },
    { city: "Can-avid", zip: "6806" },
    { city: "Dolores", zip: "6817" },
    { city: "General MacArthur", zip: "6805" },
    { city: "Giporlos", zip: "6811" },
    { city: "Guiuan", zip: "6809" },
    { city: "Hernani", zip: "6813" },
    { city: "Jipapad", zip: "6819" },
    { city: "Lawaan", zip: "6813" },
    { city: "Llorente", zip: "6812" },
    { city: "Maslog", zip: "6818" },
    { city: "Maydolong", zip: "6802" },
    { city: "Mercedes", zip: "6808" },
    { city: "Oras", zip: "6818" },
    { city: "Quinapondan", zip: "6816" },
    { city: "Salcedo", zip: "6804" },
    { city: "San Julian", zip: "6814" },
    { city: "San Policarpo", zip: "6820" },
    { city: "Sulat", zip: "6810" },
    { city: "Taft", zip: "6803" }
  ],

  /* ============================
     GUIMARAS
  ============================ */
  "Guimaras": [
    { city: "Buenavista", zip: "5044" },
    { city: "Jordan", zip: "5045" },
    { city: "Nueva Valencia", zip: "5046" },
    { city: "San Lorenzo", zip: "5048" },
    { city: "Sibunag", zip: "5047" }
  ],

  /* ============================
     IFUGAO
  ============================ */
  "Ifugao": [
    { city: "Aguinaldo", zip: "3606" },
    { city: "Alfonso Lista", zip: "3608" },
    { city: "Asipulo", zip: "3610" },
    { city: "Banaue", zip: "3601" },
    { city: "Hingyon", zip: "3607" },
    { city: "Hungduan", zip: "3603" },
    { city: "Kiangan", zip: "3604" },
    { city: "Lagawe", zip: "3600" },
    { city: "Lamut", zip: "3605" },
    { city: "Mayoyao", zip: "3602" },
    { city: "Tinoc", zip: "3611" }
  ],
  /* ============================
     ILOCOS NORTE
  ============================ */
  "Ilocos Norte": [
    { city: "Adams", zip: "2922" },
    { city: "Bacarra", zip: "2916" },
    { city: "Badoc", zip: "2904" },
    { city: "Bangui", zip: "2920" },
    { city: "Banna", zip: "2908" },
    { city: "Batac City", zip: "2906" },
    { city: "Burgos", zip: "2918" },
    { city: "Carasi", zip: "2911" },
    { city: "Currimao", zip: "2903" },
    { city: "Dingras", zip: "2913" },
    { city: "Dumalneg", zip: "2921" },
    { city: "Laoag City", zip: "2900" },
    { city: "Marcos", zip: "2907" },
    { city: "Nueva Era", zip: "2909" },
    { city: "Pagudpud", zip: "2919" },
    { city: "Paoay", zip: "2902" },
    { city: "Pasuquin", zip: "2912" },
    { city: "Piddig", zip: "2914" },
    { city: "Pinili", zip: "2905" },
    { city: "San Nicolas", zip: "2901" },
    { city: "Sarrat", zip: "2911" },
    { city: "Solsona", zip: "2910" },
    { city: "Vintar", zip: "2924" }
  ],

  /* ============================
     ILOCOS SUR
  ============================ */
  "Ilocos Sur": [
    { city: "Alilem", zip: "2716" },
    { city: "Banayoyo", zip: "2708" },
    { city: "Bantay", zip: "2727" },
    { city: "Burgos", zip: "2707" },
    { city: "Cabugao", zip: "2732" },
    { city: "Candon City", zip: "2710" },
    { city: "Caoayan", zip: "2702" },
    { city: "Cervantes", zip: "2718" },
    { city: "Galimuyod", zip: "2709" },
    { city: "Gregorio del Pilar", zip: "2720" },
    { city: "Lidlidda", zip: "2715" },
    { city: "Magsingal", zip: "2730" },
    { city: "Nagbukel", zip: "2714" },
    { city: "Narvacan", zip: "2705" },
    { city: "Quirino", zip: "2721" },
    { city: "Salcedo", zip: "2711" },
    { city: "San Emilio", zip: "2722" },
    { city: "San Esteban", zip: "2706" },
    { city: "San Ildefonso", zip: "2723" },
    { city: "San Juan", zip: "2731" },
    { city: "San Vicente", zip: "2726" },
    { city: "Santa", zip: "2703" },
    { city: "Santa Catalina", zip: "2701" },
    { city: "Santa Cruz", zip: "2713" },
    { city: "Santa Lucia", zip: "2712" },
    { city: "Santa Maria", zip: "2700" },
    { city: "Santiago", zip: "2704" },
    { city: "Santo Domingo", zip: "2729" },
    { city: "Sigay", zip: "2717" },
    { city: "Sinait", zip: "2733" },
    { city: "Sugpon", zip: "2719" },
    { city: "Suyo", zip: "2718" },
    { city: "Tagudin", zip: "2714" },
    { city: "Vigan City", zip: "2700" }
  ],

  /* ============================
     ILOILO
  ============================ */
  "Iloilo": [
    { city: "Ajuy", zip: "5012" },
    { city: "Alimodian", zip: "5028" },
    { city: "Anilao", zip: "5009" },
    { city: "Badiangan", zip: "5033" },
    { city: "Balasan", zip: "5018" },
    { city: "Banate", zip: "5010" },
    { city: "Barotac Nuevo", zip: "5007" },
    { city: "Barotac Viejo", zip: "5011" },
    { city: "Batad", zip: "5016" },
    { city: "Bingawan", zip: "5041" },
    { city: "Cabatuan", zip: "5031" },
    { city: "Calinog", zip: "5040" },
    { city: "Carles", zip: "5019" },
    { city: "Concepcion", zip: "5013" },
    { city: "Dingle", zip: "5030" },
    { city: "Dueñas", zip: "5032" },
    { city: "Dumangas", zip: "5006" },
    { city: "Estancia", zip: "5017" },
    { city: "Guimbal", zip: "5022" },
    { city: "Igbaras", zip: "5029" },
    { city: "Iloilo City", zip: "5000" },
    { city: "Janiuay", zip: "5034" },
    { city: "Lambunao", zip: "5041" },
    { city: "Leganes", zip: "5003" },
    { city: "Lemery", zip: "5042" },
    { city: "Leon", zip: "5026" },
    { city: "Maasin", zip: "5040" },
    { city: "Miagao", zip: "5023" },
    { city: "Mina", zip: "5035" },
    { city: "New Lucena", zip: "5005" },
    { city: "Oton", zip: "5020" },
    { city: "Passi City", zip: "5037" },
    { city: "Pavia", zip: "5001" },
    { city: "Pototan", zip: "5008" },
    { city: "San Dionisio", zip: "5015" },
    { city: "San Enrique", zip: "5036" },
    { city: "San Joaquin", zip: "5024" },
    { city: "San Miguel", zip: "5025" },
    { city: "San Rafael", zip: "5038" },
    { city: "Santa Barbara", zip: "5002" },
    { city: "Sara", zip: "5014" },
    { city: "Tigbauan", zip: "5021" },
    { city: "Tubungan", zip: "5027" },
    { city: "Zarraga", zip: "5004" }
  ],

  /* ============================
     ISABELA
  ============================ */
  "Isabela": [
    { city: "Alicia", zip: "3306" },
    { city: "Angadanan", zip: "3307" },
    { city: "Aurora", zip: "3316" },
    { city: "Benito Soliven", zip: "3331" },
    { city: "Burgos", zip: "3322" },
    { city: "Cabagan", zip: "3328" },
    { city: "Cabatuan", zip: "3315" },
    { city: "Cauayan City", zip: "3305" },
    { city: "Cordon", zip: "3312" },
    { city: "Delfin Albano", zip: "3326" },
    { city: "Dinapigue", zip: "3336" },
    { city: "Divilacan", zip: "3335" },
    { city: "Echague", zip: "3309" },
    { city: "Gamu", zip: "3301" },
    { city: "Ilagan City", zip: "3300" },
    { city: "Jones", zip: "3313" },
    { city: "Luna", zip: "3320" },
    { city: "Maconacon", zip: "3334" },
    { city: "Mallig", zip: "3323" },
    { city: "Naguilian", zip: "3302" },
    { city: "Palanan", zip: "3332" },
    { city: "Quezon", zip: "3324" },
    { city: "Quirino", zip: "3321" },
    { city: "Ramon", zip: "3319" },
    { city: "Reina Mercedes", zip: "3303" },
    { city: "Roxas", zip: "3320" },
    { city: "San Agustin", zip: "3314" },
    { city: "San Guillermo", zip: "3308" },
    { city: "San Isidro", zip: "3310" },
    { city: "San Manuel", zip: "3311" },
    { city: "San Mariano", zip: "3330" },
    { city: "San Mateo", zip: "3318" },
    { city: "San Pablo", zip: "3327" },
    { city: "Santa Maria", zip: "3333" },
    { city: "Santiago City", zip: "3317" },
    { city: "Tumauini", zip: "3325" }
  ],

  /* ============================
     KALINGA
  ============================ */
  "Kalinga": [
    { city: "Balbalan", zip: "3801" },
    { city: "Lubuagan", zip: "3802" },
    { city: "Pasil", zip: "3803" },
    { city: "Pinukpuk", zip: "3806" },
    { city: "Rizal", zip: "3808" },
    { city: "Tabuk City", zip: "3800" },
    { city: "Tanudan", zip: "3807" },
    { city: "Tinglayan", zip: "3805" }
  ],

  /* ============================
     LA UNION
  ============================ */
  "La Union": [
    { city: "Agoo", zip: "2504" },
    { city: "Aringay", zip: "2503" },
    { city: "Bacnotan", zip: "2515" },
    { city: "Bagulin", zip: "2512" },
    { city: "Balaoan", zip: "2517" },
    { city: "Bangar", zip: "2519" },
    { city: "Bauang", zip: "2501" },
    { city: "Burgos", zip: "2518" },
    { city: "Caba", zip: "2502" },
    { city: "Luna", zip: "2518" },
    { city: "Naguilian", zip: "2511" },
    { city: "Pugo", zip: "2508" },
    { city: "Rosario", zip: "2506" },
    { city: "San Fernando City", zip: "2500" },
    { city: "San Gabriel", zip: "2513" },
    { city: "San Juan", zip: "2514" },
    { city: "Santo Tomas", zip: "2505" },
    { city: "Santol", zip: "2516" },
    { city: "Sudipen", zip: "2519" },
    { city: "Tubao", zip: "2509" }
  ],

  /* ============================
     LAGUNA
  ============================ */
  "Laguna": [
    { city: "Alaminos", zip: "4001" },
    { city: "Bay", zip: "4033" },
    { city: "Biñan City", zip: "4024" },
    { city: "Cabuyao City", zip: "4025" },
    { city: "Calamba City", zip: "4027" },
    { city: "Calauan", zip: "4012" },
    { city: "Cavinti", zip: "4013" },
    { city: "Famy", zip: "4021" },
    { city: "Kalayaan", zip: "4015" },
    { city: "Liliw", zip: "4004" },
    { city: "Los Baños", zip: "4030" },
    { city: "Luisiana", zip: "4032" },
    { city: "Lumban", zip: "4014" },
    { city: "Mabitac", zip: "4020" },
    { city: "Magdalena", zip: "4007" },
    { city: "Majayjay", zip: "4005" },
    { city: "Nagcarlan", zip: "4002" },
    { city: "Paete", zip: "4016" },
    { city: "Pagsanjan", zip: "4008" },
    { city: "Pakil", zip: "4017" },
    { city: "Pangil", zip: "4018" },
    { city: "Pila", zip: "4010" },
    { city: "Rizal", zip: "4003" },
    { city: "San Pablo City", zip: "4000" },
    { city: "San Pedro", zip: "4023" },
    { city: "Santa Cruz", zip: "4009" },
    { city: "Santa Maria", zip: "4022" },
    { city: "Santa Rosa City", zip: "4026" },
    { city: "Siniloan", zip: "4019" },
    { city: "Victoria", zip: "4011" }
  ],

  /* ============================
     LANAO DEL NORTE
  ============================ */
  "Lanao del Norte": [
    { city: "Bacolod", zip: "9205" },
    { city: "Baloi", zip: "9217" },
    { city: "Baroy", zip: "9210" },
    { city: "Iligan City", zip: "9200" },
    { city: "Kapatagan", zip: "9214" },
    { city: "Kauswagan", zip: "9202" },
    { city: "Kolambugan", zip: "9005" },
    { city: "Lala", zip: "9211" },
    { city: "Linamon", zip: "9201" },
    { city: "Magsaysay", zip: "9714" },
    { city: "Maigo", zip: "9206" },
    { city: "Matungao", zip: "9203" },
    { city: "Munai", zip: "9212" },
    { city: "Nunungan", zip: "9216" },
    { city: "Pantao Ragat", zip: "9208" },
    { city: "Pantar", zip: "9220" },
    { city: "Poona Piagapo", zip: "9209" },
    { city: "Salvador", zip: "9221" },
    { city: "Sapad", zip: "9210" },
    { city: "Sultan Naga Dimaporo", zip: "9222" },
    { city: "Tagoloan", zip: "9223" },
    { city: "Tangcal", zip: "9215" },
    { city: "Tubod", zip: "9204" }
  ],

  /* ============================
     LANAO DEL SUR
  ============================ */
  "Lanao del Sur": [
    { city: "Balabagan", zip: "9705" },
    { city: "Balindong", zip: "9706" },
    { city: "Bayang", zip: "9708" },
    { city: "Binidayan", zip: "9709" },
    { city: "Buadiposo-Buntong", zip: "9712" },
    { city: "Bubong", zip: "9717" },
    { city: "Butig", zip: "9714" },
    { city: "Ganassi", zip: "9711" },
    { city: "Kapai", zip: "9720" },
    { city: "Kapatagan", zip: "9704" },
    { city: "Lumba-Bayabao", zip: "9718" },
    { city: "Lumbatan", zip: "9701" },
    { city: "Lumbayanague", zip: "9702" },
    { city: "Madamba", zip: "9719" },
    { city: "Madalum", zip: "9715" },
    { city: "Marantao", zip: "9709" },
    { city: "Marawi City", zip: "9700" },
    { city: "Marogong", zip: "9700" },
    { city: "Masiu", zip: "9709" },
    { city: "Mulondo", zip: "9709" },
    { city: "Pagayawan", zip: "9707" },
    { city: "Picong", zip: "9701" },
    { city: "Poona Bayabao", zip: "9716" },
    { city: "Pualas", zip: "9713" },
    { city: "Saguiaran", zip: "9701" },
    { city: "Sultan Dumalondong", zip: "9705" },
    { city: "Taraka", zip: "9720" },
    { city: "Tamparan", zip: "9701" },
    { city: "Tubaran", zip: "9721" },
    { city: "Tugaya", zip: "9714" },
    { city: "Wao", zip: "9716" }
  ],

  /* ============================
     LEYTE
  ============================ */
  "Leyte": [
    { city: "Abuyog", zip: "6510" },
    { city: "Alangalang", zip: "6517" },
    { city: "Albuera", zip: "6542" },
    { city: "Babatngon", zip: "6536" },
    { city: "Barugo", zip: "6519" },
    { city: "Bato", zip: "6525" },
    { city: "Baybay City", zip: "6521" },
    { city: "Burauen", zip: "6516" },
    { city: "Calubian", zip: "6534" },
    { city: "Capoocan", zip: "6530" },
    { city: "Carigara", zip: "6529" },
    { city: "Dagami", zip: "6515" },
    { city: "Dulag", zip: "6505" },
    { city: "Hilongos", zip: "6524" },
    { city: "Hindang", zip: "6523" },
    { city: "Inopacan", zip: "6522" },
    { city: "Isabel", zip: "6539" },
    { city: "Jaro", zip: "6527" },
    { city: "Javier", zip: "6521" },
    { city: "Julita", zip: "6506" },
    { city: "Kananga", zip: "6531" },
    { city: "La Paz", zip: "6508" },
    { city: "Leyte", zip: "6533" },
    { city: "MacArthur", zip: "6509" },
    { city: "Mahaplag", zip: "6526" },
    { city: "Matag-ob", zip: "6532" },
    { city: "Matalom", zip: "6526" },
    { city: "Mayorga", zip: "6507" },
    { city: "Merida", zip: "6533" },
    { city: "Ormoc City", zip: "6541" },
    { city: "Palo", zip: "6501" },
    { city: "Palompon", zip: "6538" },
    { city: "Pastrana", zip: "6514" },
    { city: "San Isidro", zip: "6535" },
    { city: "San Miguel", zip: "6518" },
    { city: "Santa Fe", zip: "6513" },
    { city: "Tabango", zip: "6539" },
    { city: "Tabontabon", zip: "6516" },
    { city: "Tacloban City", zip: "6500" },
    { city: "Tanauan", zip: "6502" },
    { city: "Tolosa", zip: "6503" },
    { city: "Tunga", zip: "6528" },
    { city: "Villaba", zip: "6537" }
  ],

  /* ============================
     MAGUINDANAO (BEFORE SPLIT)
  ============================ */
  "Maguindanao": [
    { city: "Ampatuan", zip: "9609" },
    { city: "Barira", zip: "9614" },
    { city: "Buldon", zip: "9612" },
    { city: "Buluan", zip: "9618" },
    { city: "Cotabato City", zip: "9600" },
    { city: "Datu Odin Sinsuat", zip: "9601" },
    { city: "Datu Paglas", zip: "9616" },
    { city: "Datu Piang", zip: "9607" },
    { city: "Datu Saudi Ampatuan", zip: "9603" },
    { city: "Gen. SK Pendatun", zip: "9619" },
    { city: "Guindulungan", zip: "9611" },
    { city: "Kabuntalan", zip: "9604" },
    { city: "Mamasapano", zip: "9613" },
    { city: "Mangudadatu", zip: "9618" },
    { city: "Marogong", zip: "9700" },
    { city: "Pagalungan", zip: "9615" },
    { city: "Paglat", zip: "9615" },
    { city: "Pandag", zip: "9616" },
    { city: "Parang", zip: "9604" },
    { city: "Rajah Buayan", zip: "9619" },
    { city: "Shariff Aguak", zip: "9609" },
    { city: "Shariff Saydona", zip: "9602" },
    { city: "South Upi", zip: "9606" },
    { city: "Sultan Kudarat", zip: "9605" },
    { city: "Sultan Mastura", zip: "9603" },
    { city: "Talayan", zip: "9602" },
    { city: "Upi", zip: "9608" }
  ],

  /* ============================
     MARINDUQUE
  ============================ */
  "Marinduque": [
    { city: "Boac", zip: "4900" },
    { city: "Buenavista", zip: "4904" },
    { city: "Gasan", zip: "4905" },
    { city: "Mogpog", zip: "4901" },
    { city: "Santa Cruz", zip: "4902" },
    { city: "Torrijos", zip: "4903" }
  ],

  /* ============================
     METRO MANILA (NCR)
  ============================ */
  "Metro Manila": [
    { city: "Caloocan", zip: "1400" },
    { city: "Las Piñas", zip: "1740" },
    { city: "Makati", zip: "1200" },
    { city: "Malabon", zip: "1470" },
    { city: "Mandaluyong", zip: "1550" },
    { city: "Manila", zip: "1000" },
    { city: "Marikina", zip: "1800" },
    { city: "Muntinlupa", zip: "1770" },
    { city: "Navotas", zip: "1485" },
    { city: "Parañaque", zip: "1700" },
    { city: "Pasay", zip: "1300" },
    { city: "Pasig", zip: "1600" },
    { city: "Pateros", zip: "1620" },
    { city: "Quezon City", zip: "1100" },
    { city: "San Juan", zip: "1500" },
    { city: "Taguig", zip: "1630" },
    { city: "Valenzuela", zip: "1440" }
  ],

  /* ============================
     MASBATE
  ============================ */
  "Masbate": [
    { city: "Aroroy", zip: "5414" },
    { city: "Baleno", zip: "5413" },
    { city: "Balud", zip: "5412" },
    { city: "Batuan", zip: "5415" },
    { city: "Cataingan", zip: "5408" },
    { city: "Cawayan", zip: "5409" },
    { city: "Claveria", zip: "5419" },
    { city: "Dimasalang", zip: "5405" },
    { city: "Esperanza", zip: "5407" },
    { city: "Mandaon", zip: "5406" },
    { city: "Masbate City", zip: "5400" },
    { city: "Milagros", zip: "5410" },
    { city: "Mobo", zip: "5401" },
    { city: "Monreal", zip: "5418" },
    { city: "Palanas", zip: "5404" },
    { city: "Pio V. Corpuz", zip: "5403" },
    { city: "Placer", zip: "5402" },
    { city: "San Fernando", zip: "5416" },
    { city: "San Jacinto", zip: "5417" },
    { city: "San Pascual", zip: "5411" },
    { city: "Uson", zip: "5405" }
  ],

  /* ============================
     MISAMIS OCCIDENTAL
  ============================ */
  "Misamis Occidental": [
    { city: "Aloran", zip: "7206" },
    { city: "Baliangao", zip: "7211" },
    { city: "Bonifacio", zip: "7215" },
    { city: "Calamba", zip: "7210" },
    { city: "Clarin", zip: "7201" },
    { city: "Concepcion", zip: "7213" },
    { city: "Don Victoriano", zip: "7203" },
    { city: "Jimenez", zip: "7204" },
    { city: "Lopez Jaena", zip: "7208" },
    { city: "Oroquieta City", zip: "7207" },
    { city: "Ozamiz City", zip: "7200" },
    { city: "Panaon", zip: "7214" },
    { city: "Plaridel", zip: "7209" },
    { city: "Sapang Dalaga", zip: "7212" },
    { city: "Sinacaban", zip: "7202" },
    { city: "Tangub City", zip: "7210" },
    { city: "Tudela", zip: "7211" }
  ],
  "Misamis Oriental": [
    { city: "Alubijid", zip: "9018" },
    { city: "Balingasag", zip: "9005" },
    { city: "Balingoan", zip: "9011" },
    { city: "Binuangan", zip: "9008" },
    { city: "Cagayan de Oro City", zip: "9000" },
    { city: "Claveria", zip: "9004" },
    { city: "El Salvador", zip: "9017" },
    { city: "Gingoog City", zip: "9014" },
    { city: "Gitagum", zip: "9020" },
    { city: "Initao", zip: "9022" },
    { city: "Jasaan", zip: "9003" },
    { city: "Kinoguitan", zip: "9009" },
    { city: "Lagonglong", zip: "9006" },
    { city: "Laguindingan", zip: "9019" },
    { city: "Libertad", zip: "9021" },
    { city: "Lugait", zip: "9025" },
    { city: "Magsaysay", zip: "9015" },
    { city: "Manticao", zip: "9024" },
    { city: "Medina", zip: "9013" },
    { city: "Naawan", zip: "9023" },
    { city: "Opol", zip: "9016" },
    { city: "Salay", zip: "9007" },
    { city: "Sugbongcogon", zip: "9002" },
    { city: "Tagoloan", zip: "9001" },
    { city: "Talisayan", zip: "9012" },
    { city: "Villanueva", zip: "9000" }
  ],

  "Mountain Province": [
    { city: "Barlig", zip: "2623" },
    { city: "Bauko", zip: "2621" },
    { city: "Besao", zip: "2618" },
    { city: "Bontoc", zip: "2616" },
    { city: "Natonin", zip: "2624" },
    { city: "Paracelis", zip: "2625" },
    { city: "Sabangan", zip: "2622" },
    { city: "Sadanga", zip: "2617" },
    { city: "Sagada", zip: "2619" },
    { city: "Tadian", zip: "2620" }
  ],

  "Negros Occidental": [
    { city: "Bacolod City", zip: "6100" },
    { city: "Bago City", zip: "6101" },
    { city: "Binalbagan", zip: "6107" },
    { city: "Cadiz City", zip: "6121" },
    { city: "Calatrava", zip: "6126" },
    { city: "Canlaon City", zip: "6130" },
    { city: "Don Salvador Benedicto", zip: "6133" },
    { city: "Enrique B. Magalona", zip: "6118" },
    { city: "Escalante City", zip: "6124" },
    { city: "Himamaylan City", zip: "6108" },
    { city: "Hinigaran", zip: "6106" },
    { city: "Hinoba-an", zip: "6110" },
    { city: "Ilog", zip: "6109" },
    { city: "Isabela", zip: "6111" },
    { city: "Kabankalan City", zip: "6112" },
    { city: "La Carlota City", zip: "6130" },
    { city: "La Castellana", zip: "6131" },
    { city: "Manapla", zip: "6110" },
    { city: "Moises Padilla", zip: "6132" },
    { city: "Murcia", zip: "6129" },
    { city: "Pontevedra", zip: "6105" },
    { city: "Pulupandan", zip: "6102" },
    { city: "Sagay City", zip: "6122" },
    { city: "San Carlos City", zip: "6127" },
    { city: "San Enrique", zip: "6104" },
    { city: "Silay City", zip: "6116" },
    { city: "Sipalay City", zip: "6113" },
    { city: "Talisay City", zip: "6115" },
    { city: "Toboso", zip: "6125" },
    { city: "Valladolid", zip: "6103" },
    { city: "Victorias City", zip: "6119" }
  ],

  "Negros Oriental": [
    { city: "Amlan", zip: "6203" },
    { city: "Ayungon", zip: "6210" },
    { city: "Bacong", zip: "6216" },
    { city: "Bais City", zip: "6206" },
    { city: "Basay", zip: "6222" },
    { city: "Bayawan City", zip: "6221" },
    { city: "Bindoy", zip: "6209" },
    { city: "Canlaon City", zip: "6223" },
    { city: "Dauin", zip: "6217" },
    { city: "Dumaguete City", zip: "6200" },
    { city: "Guihulngan City", zip: "6214" },
    { city: "Jimalalud", zip: "6212" },
    { city: "La Libertad", zip: "6213" },
    { city: "Mabinay", zip: "6207" },
    { city: "Manjuyod", zip: "6208" },
    { city: "Pamplona", zip: "6205" },
    { city: "San Jose", zip: "6202" },
    { city: "Santa Catalina", zip: "6220" },
    { city: "Siaton", zip: "6219" },
    { city: "Sibulan", zip: "6201" },
    { city: "Tanjay City", zip: "6204" },
    { city: "Tayasan", zip: "6211" },
    { city: "Valencia", zip: "6215" },
    { city: "Vallehermoso", zip: "6224" },
    { city: "Zamboanguita", zip: "6218" }
  ],

  "Northern Samar": [
    { city: "Allen", zip: "6405" },
    { city: "Biri", zip: "6410" },
    { city: "Bobon", zip: "6401" },
    { city: "Capul", zip: "6408" },
    { city: "Catarman", zip: "6400" },
    { city: "Catubig", zip: "6417" },
    { city: "Gamay", zip: "6422" },
    { city: "Laoang", zip: "6411" },
    { city: "Lapinig", zip: "6423" },
    { city: "Las Navas", zip: "6419" },
    { city: "Lavezares", zip: "6404" },
    { city: "Lope de Vega", zip: "6403" },
    { city: "Mapanas", zip: "6421" },
    { city: "Mondragon", zip: "6415" },
    { city: "Palapag", zip: "6420" },
    { city: "Pambujan", zip: "6413" },
    { city: "Rosario", zip: "6416" },
    { city: "San Antonio", zip: "6407" },
    { city: "San Isidro", zip: "6409" },
    { city: "San Jose", zip: "6402" },
    { city: "San Roque", zip: "6414" },
    { city: "San Vicente", zip: "6406" },
    { city: "Silvino Lobos", zip: "6418" },
    { city: "Victoria", zip: "6412" }
  ],

  "Nueva Ecija": [
    { city: "Aliaga", zip: "3111" },
    { city: "Bongabon", zip: "3128" },
    { city: "Cabanatuan City", zip: "3100" },
    { city: "Cabiao", zip: "3107" },
    { city: "Carranglan", zip: "3123" },
    { city: "Cuyapo", zip: "3117" },
    { city: "Gabaldon", zip: "3131" },
    { city: "Gapan City", zip: "3105" },
    { city: "General Mamerto Natividad", zip: "3125" },
    { city: "General Tinio", zip: "3104" },
    { city: "Guimba", zip: "3115" },
    { city: "Jaen", zip: "3109" },
    { city: "Laur", zip: "3129" },
    { city: "Licab", zip: "3112" },
    { city: "Llanera", zip: "3126" },
    { city: "Lupao", zip: "3122" },
    { city: "Muñoz City", zip: "3113" },
    { city: "Nampicuan", zip: "3116" },
    { city: "Palayan City", zip: "3132" },
    { city: "Pantabangan", zip: "3124" },
    { city: "Penaranda", zip: "3103" },
    { city: "Quezon", zip: "3114" },
    { city: "Rizal", zip: "3127" },
    { city: "San Antonio", zip: "3108" },
    { city: "San Isidro", zip: "3106" },
    { city: "San Jose City", zip: "3121" },
    { city: "San Leonardo", zip: "3102" },
    { city: "Santa Rosa", zip: "3101" },
    { city: "Santo Domingo", zip: "3133" },
    { city: "Talavera", zip: "3110" },
    { city: "Talugtug", zip: "3118" },
    { city: "Zaragoza", zip: "3111" }
  ],

  "Pampanga": [
  { city: "Angeles City", zip: "2009" },
  { city: "Apalit", zip: "2016" },
  { city: "Arayat", zip: "2012" },
  { city: "Bacolor", zip: "2001" },
  { city: "Candaba", zip: "2013" },
  { city: "Floridablanca", zip: "2006" },
  { city: "Guagua", zip: "2003" },
  { city: "Lubao", zip: "2005" },
  { city: "Mabalacat City", zip: "2010" },
  { city: "Macabebe", zip: "2018" },
  { city: "Magalang", zip: "2011" },
  { city: "Masantol", zip: "2017" },
  { city: "Mexico", zip: "2021" },
  { city: "Minalin", zip: "2019" },
  { city: "Porac", zip: "2008" },
  { city: "San Fernando City", zip: "2000" },
  { city: "San Luis", zip: "2014" },
  { city: "San Simon", zip: "2015" },
  { city: "Santa Ana", zip: "2022" },
  { city: "Santa Rita", zip: "2002" },
  { city: "Santo Tomas", zip: "2020" },
  { city: "Sasmuan", zip: "2004" }
],

"Pangasinan": [
  { city: "Dagupan City", zip: "2400" },
  { city: "San Carlos City", zip: "2420" },
  { city: "Urdaneta City", zip: "2428" },
  { city: "Lingayen", zip: "2401" },
  { city: "Alaminos City", zip: "2404" },
  { city: "Binmaley", zip: "2417" },
  { city: "Binalonan", zip: "2436" },
  { city: "Bayambang", zip: "2423" },
  { city: "Bautista", zip: "2424" },
  { city: "Calasiao", zip: "2418" },
  { city: "Dagupan", zip: "2400" },
  { city: "Laoac", zip: "2437" },
  { city: "Malasiqui", zip: "2421" },
  { city: "Manaoag", zip: "2430" },
  { city: "Mangaldan", zip: "2432" },
  { city: "Mangatarem", zip: "2413" },
  { city: "Mapandan", zip: "2429" },
  { city: "Pozorrubio", zip: "2435" },
  { city: "Rosales", zip: "2441" },
  { city: "San Fabian", zip: "2433" },
  { city: "San Jacinto", zip: "2431" },
  { city: "San Manuel", zip: "2438" },
  { city: "San Nicolas", zip: "2447" },
  { city: "Sison", zip: "2434" },
  { city: "Sta. Barbara", zip: "2419" },
  { city: "Sto. Tomas", zip: "2426" },
  { city: "Tayug", zip: "2445" },
  { city: "Umingan", zip: "2442" },
  { city: "Urbiztondo", zip: "2414" },
  { city: "Villasis", zip: "2427" }
],"Quezon": [
  { city: "Agdangan", zip: "4304" },
  { city: "Alabat", zip: "4333" },
  { city: "Atimonan", zip: "4331" },
  { city: "Buenavista", zip: "4320" },
  { city: "Burdeos", zip: "4340" },
  { city: "Calauag", zip: "4318" },
  { city: "Candelaria", zip: "4323" },
  { city: "Catanauan", zip: "4311" },
  { city: "Dolores", zip: "4326" },
  { city: "General Luna", zip: "4310" },
  { city: "General Nakar", zip: "4338" },
  { city: "Guinayangan", zip: "4319" },
  { city: "Gumaca", zip: "4307" },
  { city: "Infanta", zip: "4336" },
  { city: "Jomalig", zip: "4342" },
  { city: "Lopez", zip: "4316" },
  { city: "Lucban", zip: "4328" },
  { city: "Lucena City", zip: "4301" },
  { city: "Macalelon", zip: "4309" },
  { city: "Mauban", zip: "4330" },
  { city: "Mulanay", zip: "4312" },
  { city: "Padre Burgos", zip: "4303" },
  { city: "Pagbilao", zip: "4302" },
  { city: "Panukulan", zip: "4341" },
  { city: "Patnanungan", zip: "4343" },
  { city: "Perez", zip: "4334" },
  { city: "Pitogo", zip: "4308" },
  { city: "Plaridel", zip: "4306" },
  { city: "Polillo", zip: "4339" },
  { city: "Quezon", zip: "4332" },
  { city: "Real", zip: "4335" },
  { city: "Sampaloc", zip: "4327" },
  { city: "San Andres", zip: "4314" },
  { city: "San Antonio", zip: "4324" },
  { city: "San Francisco", zip: "4315" },
  { city: "San Narciso", zip: "4313" },
  { city: "Sariaya", zip: "4322" },
  { city: "Tagkawayan", zip: "4321" },
  { city: "Tayabas City", zip: "4329" },
  { city: "Tiaong", zip: "4325" },
  { city: "Unisan", zip: "4305" }
],

"Quirino": [
  { city: "Aglipay", zip: "3403" },
  { city: "Cabarroguis", zip: "3400" },
  { city: "Diffun", zip: "3401" },
  { city: "Maddela", zip: "3404" },
  { city: "Nagtipunan", zip: "3405" },
  { city: "Saguday", zip: "3402" }
],
"Rizal": [
  { city: "Angono", zip: "1930" },
  { city: "Antipolo City", zip: "1870" },
  { city: "Baras", zip: "1970" },
  { city: "Binangonan", zip: "1940" },
  { city: "Cainta", zip: "1900" },
  { city: "Cardona", zip: "1950" },
  { city: "Jalajala", zip: "1990" },
  { city: "Morong", zip: "1960" },
  { city: "Pililla", zip: "1910" },
  { city: "Rodriguez (Montalban)", zip: "1860" },
  { city: "San Mateo", zip: "1850" },
  { city: "Tanay", zip: "1980" },
  { city: "Taytay", zip: "1920" },
  { city: "Teresa", zip: "1880" }
],
"Romblon": [
  { city: "Alcantara", zip: "5509" },
  { city: "Banton", zip: "5515" },
  { city: "Cajidiocan", zip: "5512" },
  { city: "Calatrava", zip: "5503" },
  { city: "Concepcion", zip: "5506" },
  { city: "Corcuera", zip: "5514" },
  { city: "Ferrol", zip: "5507" },
  { city: "Looc", zip: "5504" },
  { city: "Magdiwang", zip: "5511" },
  { city: "Odiongan", zip: "5505" },
  { city: "Romblon", zip: "5500" },
  { city: "San Agustin", zip: "5501" },
  { city: "San Andres", zip: "5502" },
  { city: "San Fernando", zip: "5513" },
  { city: "Santa Fe", zip: "5508" },
  { city: "Santa Maria", zip: "5510" }
],
"Samar": [
  { city: "Almagro", zip: "6724" },
  { city: "Basey", zip: "6720" },
  { city: "Calbayog City", zip: "6710" },
  { city: "Calbiga", zip: "6715" },
  { city: "Catbalogan City", zip: "6700" },
  { city: "Daram", zip: "6722" },
  { city: "Gandara", zip: "6716" },
  { city: "Hinabangan", zip: "6713" },
  { city: "Jiabong", zip: "6701" },
  { city: "Marabut", zip: "6721" },
  { city: "Matuguinao", zip: "6711" },
  { city: "Motiong", zip: "6702" },
  { city: "Pagsanghan", zip: "6714" },
  { city: "Paranas", zip: "6703" },
  { city: "Pinabacdao", zip: "6712" },
  { city: "San Jorge", zip: "6707" },
  { city: "San Jose de Buan", zip: "6723" },
  { city: "San Sebastian", zip: "6706" },
  { city: "Santa Margarita", zip: "6709" },
  { city: "Santa Rita", zip: "6718" },
  { city: "Santo Niño", zip: "6708" },
  { city: "Tagapul-an", zip: "6725" },
  { city: "Talalora", zip: "6719" },
  { city: "Tarangnan", zip: "6704" },
  { city: "Villareal", zip: "6717" },
  { city: "Zumarraga", zip: "6705" }
],

"Sarangani": [
  { city: "Alabel", zip: "9501" },
  { city: "Glan", zip: "9517" },
  { city: "Kiamba", zip: "9514" },
  { city: "Maasim", zip: "9502" },
  { city: "Maitum", zip: "9515" },
  { city: "Malapatan", zip: "9516" },
  { city: "Malungon", zip: "9503" }
],
"Siquijor": [
  { city: "Siquijor", zip: "6225" },
  { city: "Larena", zip: "6226" },
  { city: "Enrique Villanueva", zip: "6220" },
  { city: "Maria", zip: "6229" },
  { city: "Lazi", zip: "6228" },
  { city: "San Juan", zip: "6227" }
],
"Sorsogon": [
  { city: "Sorsogon City", zip: "4700" },
  { city: "Barcelona", zip: "4712" },
  { city: "Bulan", zip: "4706" },
  { city: "Bulusan", zip: "4704" },
  { city: "Casiguran", zip: "4702" },
  { city: "Castilla", zip: "4713" },
  { city: "Donsol", zip: "4715" },
  { city: "Gubat", zip: "4710" },
  { city: "Irosin", zip: "4707" },
  { city: "Juban", zip: "4703" },
  { city: "Magallanes", zip: "4705" },
  { city: "Matnog", zip: "4708" },
  { city: "Pilar", zip: "4714" },
  { city: "Prieto Diaz", zip: "4711" },
  { city: "Sta. Magdalena", zip: "4709" }
],
"South Cotabato": [
  { city: "Banga", zip: "9511" },
  { city: "General Santos City", zip: "9500" },
  { city: "Koronadal City", zip: "9506" },
  { city: "Lake Sebu", zip: "9514" },
  { city: "Norala", zip: "9508" },
  { city: "Polomolok", zip: "9504" },
  { city: "Santo Niño", zip: "9509" },
  { city: "Surallah", zip: "9512" },
  { city: "Tampakan", zip: "9507" },
  { city: "Tantangan", zip: "9510" },
  { city: "Tupi", zip: "9505" }
],
"Southern Leyte": [
  { city: "Maasin City", zip: "6600" },
  { city: "Anahawan", zip: "6610" },
  { city: "Bontoc", zip: "6604" },
  { city: "Hinunangan", zip: "6608" },
  { city: "Hinundayan", zip: "6609" },
  { city: "Libagon", zip: "6615" },
  { city: "Liloan", zip: "6612" },
  { city: "Limasawa", zip: "6618" },
  { city: "Macrohon", zip: "6601" },
  { city: "Malitbog", zip: "6603" },
  { city: "Padre Burgos", zip: "6602" },
  { city: "Pintuyan", zip: "6614" },
  { city: "San Francisco", zip: "6613" },
  { city: "San Juan", zip: "6611" },
  { city: "San Ricardo", zip: "6617" },
  { city: "Silago", zip: "6607" },
  { city: "Sogod", zip: "6606" },
  { city: "St. Bernard", zip: "6616" }
],
"Sultan Kudarat": [
  { city: "Bagumbayan", zip: "9810" },
  { city: "Columbio", zip: "9801" },
  { city: "Esperanza", zip: "9806" },
  { city: "Isulan", zip: "9805" },
  { city: "Kalamansig", zip: "9808" },
  { city: "Lambayong", zip: "9802" },
  { city: "Lebak", zip: "9811" },
  { city: "Lutayan", zip: "9803" },
  { city: "Palimbang", zip: "9809" },
  { city: "President Quirino", zip: "9804" },
  { city: "Sen. Ninoy Aquino", zip: "9807" },
  { city: "Tacurong City", zip: "9800" }
],
"Sulu": [
  { city: "Banguingui", zip: "7402" },
  { city: "Hadji Panglima Tahil", zip: "7401" },
  { city: "Indanan", zip: "7407" },
  { city: "Jolo", zip: "7400" },
  { city: "Kalingalan Caluang", zip: "7411" },
  { city: "Lugus", zip: "7410" },
  { city: "Luuk", zip: "7404" },
  { city: "Maimbung", zip: "7405" },
  { city: "Old Panamao", zip: "7415" },
  { city: "Omar", zip: "7413" },
  { city: "Pandami", zip: "7409" },
  { city: "Panglima Estino", zip: "7408" },
  { city: "Pangutaran", zip: "7403" },
  { city: "Parang", zip: "7406" },
  { city: "Patikul", zip: "7414" },
  { city: "Siasi", zip: "7412" },
  { city: "Talipao", zip: "7408" },
  { city: "Tapul", zip: "7409" }
],

"Surigao del Norte": [
  { city: "Surigao City", zip: "8400" },
  { city: "Alegria", zip: "8425" },
  { city: "Bacuag", zip: "8408" },
  { city: "Burgos", zip: "8424" },
  { city: "Claver", zip: "8410" },
  { city: "Dapa", zip: "8417" },
  { city: "Del Carmen", zip: "8418" },
  { city: "General Luna", zip: "8419" },
  { city: "Gigaquit", zip: "8409" },
  { city: "Mainit", zip: "8407" },
  { city: "Malimono", zip: "8402" },
  { city: "Pilar", zip: "8420" },
  { city: "Placer", zip: "8405" },
  { city: "San Benito", zip: "8423" },
  { city: "San Francisco", zip: "8401" },
  { city: "San Isidro", zip: "8421" },
  { city: "Santa Monica", zip: "8422" },
  { city: "Sison", zip: "8404" },
  { city: "Socorro", zip: "8416" },
  { city: "Tagana-an", zip: "8406" },
  { city: "Tubod", zip: "8403" }
],
"Surigao del Sur": [
  { city: "Tandag City", zip: "8300" },
  { city: "Bislig City", zip: "8311" },
  { city: "Barobo", zip: "8309" },
  { city: "Bayabas", zip: "8303" },
  { city: "Cagwait", zip: "8304" },
  { city: "Cantilan", zip: "8317" },
  { city: "Carmen", zip: "8315" },
  { city: "Carrascal", zip: "8318" },
  { city: "Cortes", zip: "8313" },
  { city: "Hinatuan", zip: "8310" },
  { city: "Lanuza", zip: "8314" },
  { city: "Lianga", zip: "8307" },
  { city: "Lingig", zip: "8312" },
  { city: "Madrid", zip: "8316" },
  { city: "Marihatag", zip: "8306" },
  { city: "San Agustin", zip: "8305" },
  { city: "San Miguel", zip: "8301" },
  { city: "Tagbina", zip: "8308" },
  { city: "Tago", zip: "8302" }
],

"Tarlac": [
  { city: "Anao", zip: "2310" },
  { city: "Bamban", zip: "2317" },
  { city: "Camiling", zip: "2306" },
  { city: "Capas", zip: "2315" },
  { city: "Concepcion", zip: "2316" },
  { city: "Gerona", zip: "2302" },
  { city: "La Paz", zip: "2314" },
  { city: "Mayantoc", zip: "2304" },
  { city: "Moncada", zip: "2308" },
  { city: "Paniqui", zip: "2307" },
  { city: "Pura", zip: "2312" },
  { city: "Ramos", zip: "2311" },
  { city: "San Clemente", zip: "2305" },
  { city: "San Manuel", zip: "2309" },
  { city: "Santa Ignacia", zip: "2303" },
  { city: "Tarlac City", zip: "2300" },
  { city: "Victoria", zip: "2313" }
],
"Tawi-Tawi": [
  { city: "Bongao", zip: "7500" },
  { city: "Languyan", zip: "7509" },
  { city: "Mapun", zip: "7515" },
  { city: "Panglima Sugala", zip: "7501" },
  { city: "Sapa-Sapa", zip: "7503" },
  { city: "Sibutu", zip: "7504" },
  { city: "Simunul", zip: "7505" },
  { city: "Sitangkai", zip: "7506" },
  { city: "South Ubian", zip: "7502" },
  { city: "Tandubas", zip: "7507" },
  { city: "Turtle Islands", zip: "7511" }
],

"Zambales": [
  { city: "Botolan", zip: "2202" },
  { city: "Cabangan", zip: "2203" },
  { city: "Candelaria", zip: "2212" },
  { city: "Castillejos", zip: "2208" },
  { city: "Iba", zip: "2201" },
  { city: "Masinloc", zip: "2211" },
  { city: "Olongapo City", zip: "2200" },
  { city: "Palauig", zip: "2210" },
  { city: "San Antonio", zip: "2206" },
  { city: "San Felipe", zip: "2204" },
  { city: "San Marcelino", zip: "2207" },
  { city: "San Narciso", zip: "2205" },
  { city: "Santa Cruz", zip: "2213" },
  { city: "Subic", zip: "2209" }
],
"Zamboanga del Norte": [
  { city: "Baliguian", zip: "7123" },
  { city: "Dapitan City", zip: "7101" },
  { city: "Dipolog City", zip: "7100" },
  { city: "Godod", zip: "7121" },
  { city: "Gutalac", zip: "7122" },
  { city: "Jose Dalman", zip: "7111" },
  { city: "Kalawit", zip: "7124" },
  { city: "Katipunan", zip: "7109" },
  { city: "La Libertad", zip: "7119" },
  { city: "Labason", zip: "7117" },
  { city: "Leon B. Postigo", zip: "7110" },
  { city: "Liloy", zip: "7115" },
  { city: "Manukan", zip: "7110" },
  { city: "Mutia", zip: "7107" },
  { city: "Piñan", zip: "7105" },
  { city: "Polanco", zip: "7106" },
  { city: "Pres. Manuel Roxas", zip: "7116" },
  { city: "Rizal", zip: "7104" },
  { city: "Salug", zip: "7114" },
  { city: "Sergio Osmeña", zip: "7108" },
  { city: "Siayan", zip: "7113" },
  { city: "Sibuco", zip: "7120" },
  { city: "Sibutad", zip: "7103" },
  { city: "Sindangan", zip: "7112" },
  { city: "Siocon", zip: "7129" },
  { city: "Sirawai", zip: "7121" },
  { city: "Tampilisan", zip: "7118" }
],
"Zamboanga del Sur": [
  { city: "Aurora", zip: "7020" },
  { city: "Bayog", zip: "7011" },
  { city: "Dimataling", zip: "7032" },
  { city: "Dinas", zip: "7030" },
  { city: "Dumalinao", zip: "7015" },
  { city: "Dumingag", zip: "7028" },
  { city: "Guipos", zip: "7043" },
  { city: "Josefina", zip: "7027" },
  { city: "Kumalarang", zip: "7013" },
  { city: "Labangan", zip: "7017" },
  { city: "Lakewood", zip: "7014" },
  { city: "Lapuyan", zip: "7037" },
  { city: "Mahayag", zip: "7026" },
  { city: "Malabang (historic overlap)", zip: "9300" },
  { city: "Margosatubig", zip: "7035" },
  { city: "Midsalip", zip: "7021" },
  { city: "Molave", zip: "7023" },
  { city: "Pagadian City", zip: "7016" },
  { city: "Pitogo", zip: "7033" },
  { city: "Ramon Magsaysay", zip: "7024" },
  { city: "San Miguel", zip: "7029" },
  { city: "San Pablo", zip: "7031" },
  { city: "Sominot", zip: "7022" },
  { city: "Tabina", zip: "7034" },
  { city: "Tigbao", zip: "7018" },
  { city: "Tukuran", zip: "7019" },
  { city: "Vincenzo A. Sagun", zip: "7036" },
  { city: "Zamboanga City", zip: "7000" }
],

  "Zamboanga Sibugay": [
    { city: "Alicia", zip: "7040" },
    { city: "Buug", zip: "7009" },
    { city: "Diplahan", zip: "7039" },
    { city: "Imelda", zip: "7038" },
    { city: "Ipil", zip: "7001" },
    { city: "Kabasalan", zip: "7005" },
    { city: "Mabuhay", zip: "7010" },
    { city: "Malangas", zip: "7037" },
    { city: "Naga", zip: "7035" },
    { city: "Olutanga", zip: "7041" },
    { city: "Payao", zip: "7008" },
    { city: "Roseller Lim", zip: "7007" },
    { city: "Siay", zip: "7006" },
    { city: "Talusan", zip: "7042" },
    { city: "Tungawan", zip: "7003" }
  ]
};